/* Generated by make-bootanim from discover.png. 1 frame(s), 128x64 1bpp.
 * At each of the intro's panel presents it copies the next frame over the
 * composed frame, then runs the stock present. */
        .section .run, "ax"

        .globl  discover_diff
        .globl  discover_flush

discover_diff:
        bsr     discover_advance
        jmp     0x400e60e2

discover_flush:
        bsr     discover_advance
        jmp     0x400e6064

discover_advance:
        move.l  0x40000340,%d0          /* PIT3 vector slot */
        cmpi.l  #0x4006c154,%d0
        bne.s   9f
        move.l  0x4020d8f8,%a0          /* fb_front */
        tst.l   %a0
        beq.s   9f
        move.l  discover_idx,%d0
        addq.l  #1,%d0
        cmpi.l  #1,%d0
        bne.s   1f
        clr.l   %d0
1:      move.l  %d0,discover_idx
        lsl.l   #8,%d0                  /* * 1024 = <<8 then <<2 */
        lsl.l   #2,%d0
        add.l   #discover_frames,%d0
        movea.l %d0,%a1
        move.l  #256,%d0
2:      move.l  (%a1)+,(%a0)+
        subq.l  #1,%d0
        bne.s   2b
9:      rts

        .balign 4
discover_idx:
        .long   0
        .balign 4
discover_frames:
        .incbin "frames.bin"
