/* Generated by make-bootanim from tumblr_n8ggiogZGX1rmhormo1_1280.gif. 41 frame(s), 128x64 1bpp.
 * At each of the intro's panel presents it copies the next frame over the
 * composed frame, then runs the stock present. */
        .section .run, "ax"

        .globl  match_diff
        .globl  match_flush

match_diff:
        bsr     match_advance
        jmp     0x400f8efa

match_flush:
        bsr     match_advance
        jmp     0x400f8e7c

match_advance:
        move.l  0x40000340,%d0          /* PIT3 vector slot */
        cmpi.l  #0x40090cdc,%d0
        bne.s   9f
        move.l  0x40241a44,%a0          /* fb_front */
        tst.l   %a0
        beq.s   9f
        move.l  match_idx,%d0
        addq.l  #1,%d0
        cmpi.l  #41,%d0
        bne.s   1f
        clr.l   %d0
1:      move.l  %d0,match_idx
        lsl.l   #8,%d0                  /* * 1024 = <<8 then <<2 */
        lsl.l   #2,%d0
        add.l   #match_frames,%d0
        movea.l %d0,%a1
        move.l  #256,%d0
2:      move.l  (%a1)+,(%a0)+
        subq.l  #1,%d0
        bne.s   2b
9:      rts

        .balign 4
match_idx:
        .long   0
        .balign 4
match_frames:
        .incbin "frames.bin"
