/* Generated by make-bootanim from Primp.gif. 59 frame(s), 128x64 1bpp.
 * At each of the intro's panel presents it copies the next frame over the
 * composed frame, then runs the stock present. */
        .section .run, "ax"

        .globl  tussy_diff
        .globl  tussy_flush

tussy_diff:
        bsr     tussy_advance
        jmp     0x400f8efa

tussy_flush:
        bsr     tussy_advance
        jmp     0x400f8e7c

tussy_advance:
        move.l  0x40000340,%d0          /* PIT3 vector slot */
        cmpi.l  #0x40090cdc,%d0
        bne.s   9f
        move.l  0x40241a44,%a0          /* fb_front */
        tst.l   %a0
        beq.s   9f
        move.l  tussy_idx,%d0
        addq.l  #1,%d0
        cmpi.l  #59,%d0
        bne.s   1f
        clr.l   %d0
1:      move.l  %d0,tussy_idx
        lsl.l   #8,%d0                  /* * 1024 = <<8 then <<2 */
        lsl.l   #2,%d0
        add.l   #tussy_frames,%d0
        movea.l %d0,%a1
        move.l  #256,%d0
2:      move.l  (%a1)+,(%a0)+
        subq.l  #1,%d0
        bne.s   2b
9:      rts

        .balign 4
tussy_idx:
        .long   0
        .balign 4
tussy_frames:
        .incbin "frames.bin"
