#!/usr/bin/env python3
"""Turn a PNG or GIF into a multi-frame boot-splash mod for the Digitakt mk1
or Digitone mk1.

It writes a ready-to-build elekloader mod folder: a GIF's frames (or a PNG's
single image) packed to the 128x64 panel format, an assembly stub that cycles
them at the intro's panel presents, and a mod.json with the device's sites.
Build and install it with elekloader; see ../docs/BUILDING.md and
../docs/INSTALLING.md, or the README it writes.

    python make_bootanim.py logo.png
    python make_bootanim.py anim.gif --dn -o my-bootanim
    python make_bootanim.py --text "HELLO" --frames 1

Run it through make-bootanim.bat, or directly. Needs Pillow.
"""
import argparse
import os
import re
import sys

W, H = 128, 64
FRAME = W * H // 8  # 1024 bytes

# Per device: the intro's present call sites, their stock `jsr` bytes, the
# present function entries, the fb_front pointer global and the intro PIT3
# handler. Same values as the hand-written mods under ../mods and
# ../digitone1/mods.
DT = dict(
    device='digitakt-mk1', os='1.53',
    diff=0x400e60e2, flush=0x400e6064,
    diff_sites=[0x4006c2d0, 0x4006c3ac, 0x4006c864, 0x4006cb68],
    flush_sites=[0x4006c3a4, 0x4006c85c, 0x4006cb60],
    diff_call='4eb9400e60e2', flush_call='4eb9400e6064',
    fb_front=0x4020d8f8, intro_isr=0x4006c154,
)
DN = dict(
    device='digitone-mk1', os='1.43',
    diff=0x400f8efa, flush=0x400f8e7c,
    diff_sites=[0x40090e58, 0x40091000, 0x4009130a, 0x400917bc, 0x40091ac0],
    flush_sites=[0x40090ff8, 0x40091302, 0x400917b4, 0x40091ab8],
    diff_call='4eb9400f8efa', flush_call='4eb9400f8e7c',
    fb_front=0x40241a44, intro_isr=0x40090cdc,
)


def fit(img):
    """Scale to fit 128x64, preserving aspect, centred on a black canvas."""
    from PIL import Image
    img = img.convert('L')
    scale = min(W / img.width, H / img.height)
    nw, nh = max(1, round(img.width * scale)), max(1, round(img.height * scale))
    img = img.resize((nw, nh))
    canvas = Image.new('L', (W, H), 0)
    canvas.paste(img, ((W - nw) // 2, (H - nh) // 2))
    return canvas


def pack_one(img, invert=False, dither=False):
    """A Pillow image -> 1024 bytes in the panel format.

    byte = page + 8*column, page = 7 - (y>>3), bit = y&7 (LSB first)."""
    img = fit(img)
    if invert:
        img = img.point(lambda v: 255 - v)
    one = img.convert('1') if dither else \
        img.point(lambda v: 255 if v > 127 else 0).convert('1')
    px = one.load()
    buf = bytearray(FRAME)
    for y in range(H):
        page, bit = 7 - (y >> 3), y & 7
        for x in range(W):
            if px[x, y]:
                buf[page + 8 * x] |= 1 << bit
    return bytes(buf)


def text_frame(s):
    """Render `s` with Pillow's built-in font, scaled up to be readable."""
    from PIL import Image, ImageDraw
    box = ImageDraw.Draw(Image.new('L', (1, 1))).textbbox((0, 0), s)
    tw, th = max(1, box[2] - box[0]), max(1, box[3] - box[1])
    src = Image.new('L', (tw, th), 0)
    ImageDraw.Draw(src).text((-box[0], -box[1]), s, fill=255)
    scale = max(1, min(W // tw, H // th))
    src = src.resize((tw * scale, th * scale))
    canvas = Image.new('L', (W, H), 0)
    canvas.paste(src, ((W - src.width) // 2, (H - src.height) // 2))
    return canvas


def load_frames(path, text):
    from PIL import Image, ImageSequence
    if text is not None:
        return [text_frame(text)]
    im = Image.open(path)
    if getattr(im, 'is_animated', False) and getattr(im, 'n_frames', 1) > 1:
        return [f.copy() for f in ImageSequence.Iterator(im)]
    return [im.copy()]


def decimate(frames, limit):
    """Keep at most `limit` frames, evenly spaced."""
    if limit <= 0 or len(frames) <= limit:
        return frames, False
    step = len(frames) / limit
    return [frames[int(i * step)] for i in range(limit)], True


def slug(s):
    s = re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')
    return s or 'bootanim'


ASM = '''/* Generated by make-bootanim from {src}. {n} frame(s), 128x64 1bpp.
 * At each of the intro's panel presents it copies the next frame over the
 * composed frame, then runs the stock present. */
        .section .run, "ax"

        .globl  {p}_diff
        .globl  {p}_flush

{p}_diff:
        bsr     {p}_advance
        jmp     0x{diff:08x}

{p}_flush:
        bsr     {p}_advance
        jmp     0x{flush:08x}

{p}_advance:
        move.l  0x40000340,%d0          /* PIT3 vector slot */
        cmpi.l  #0x{isr:08x},%d0
        bne.s   9f
        move.l  0x{fb:08x},%a0          /* fb_front */
        tst.l   %a0
        beq.s   9f
        move.l  {p}_idx,%d0
        addq.l  #1,%d0
        cmpi.l  #{n},%d0
        bne.s   1f
        clr.l   %d0
1:      move.l  %d0,{p}_idx
        lsl.l   #8,%d0                  /* * 1024 = <<8 then <<2 */
        lsl.l   #2,%d0
        add.l   #{p}_frames,%d0
        movea.l %d0,%a1
        move.l  #256,%d0
2:      move.l  (%a1)+,(%a0)+
        subq.l  #1,%d0
        bne.s   2b
9:      rts

        .balign 4
{p}_idx:
        .long   0
        .balign 4
{p}_frames:
        .incbin "frames.bin"
'''


def site(addr, call, target):
    return {'addr': '0x%08x' % addr, 'stock': call, 'op': 'jsr', 'target': target}


def write_mod(outdir, name, id, src, frames, dev):
    os.makedirs(outdir, exist_ok=True)
    p = id.replace('-', '_')
    data = b''.join(frames)
    with open(os.path.join(outdir, 'frames.bin'), 'wb') as fh:
        fh.write(data)
    asm = ASM.format(src=os.path.basename(src), n=len(frames), p=p,
                     diff=dev['diff'], flush=dev['flush'],
                     isr=dev['intro_isr'], fb=dev['fb_front'])
    with open(os.path.join(outdir, 'splash.s'), 'w') as fh:
        fh.write(asm)
    sites = [site(a, dev['diff_call'], p + '_diff') for a in dev['diff_sites']] \
        + [site(a, dev['flush_call'], p + '_flush') for a in dev['flush_sites']]
    mod = {
        'id': id, 'version': '1.0', 'title': name, 'category': 'Boot',
        'author': 'make-bootanim', 'license': 'GPL-2.0-or-later',
        'description': 'Boot animation generated from %s (%d frame%s). '
                       'Drawn over the intro panel while it is live.'
                       % (os.path.basename(src), len(frames),
                          '' if len(frames) == 1 else 's'),
        'device': dev['device'], 'os': dev['os'],
        'sources': ['splash.s'],
        'sites': sites,
        'requires': ['core'], 'resources': {'names': []},
    }
    import json
    with open(os.path.join(outdir, 'mod.json'), 'w') as fh:
        fh.write(json.dumps(mod, indent=1) + '\n')
    core = 'core-2.1' if dev['device'] == 'digitakt-mk1' else 'core-dn1-2.0a'
    core_dir = 'core' if dev['device'] == 'digitakt-mk1' else 'core-dn1'
    with open(os.path.join(outdir, 'README.md'), 'w') as fh:
        fh.write(
            '# %s\n\nGenerated from `%s` (%d frame%s) by make-bootanim.\n\n'
            'Build it with elekloader, then patch it with %s:\n\n'
            '```sh\ncd elekloader\n'
            'python -m elekloader.sdk.build <this dir> --stock <stock .syx>\n'
            'python -m elekloader.patch --stock <stock .syx> \\\n'
            '    --mod mods/%s/out/%s.elemod \\\n'
            '    --mod <this dir>/out/%s-1.0.elemod --out out.syx --version 2.0x\n'
            '```\n' % (name, os.path.basename(src), len(frames),
                      '' if len(frames) == 1 else 's',
                      core_dir, core_dir, core, id))
    return id


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('input', nargs='?', help='a PNG, GIF, ... (omit with --text)')
    ap.add_argument('-o', '--out', help='output mod folder (default <name>-bootanim)')
    ap.add_argument('--name', help='mod name/title (default from the file)')
    ap.add_argument('--dn', action='store_true', help='Digitone mk1 (1.43) instead of Digitakt mk1 (1.53)')
    ap.add_argument('--frames', type=int, default=60, help='max frames to keep (default 60)')
    ap.add_argument('--invert', action='store_true', help='swap ink and paper')
    ap.add_argument('--dither', action='store_true', help='Floyd-Steinberg instead of threshold')
    ap.add_argument('--text', help='render this text instead of an image')
    a = ap.parse_args()

    if not a.text and not a.input:
        ap.error('give an input image/gif, or --text')

    base = os.path.splitext(os.path.basename(a.input or a.text))[0]
    name = a.name or (a.text if a.text else base)
    id = slug(name)
    outdir = a.out or (id + '-bootanim')
    dev = DN if a.dn else DT

    raw = load_frames(a.input, a.text)
    frames, dropped = decimate(raw, a.frames)
    packed = [pack_one(f, a.invert, a.dither) for f in frames]
    write_mod(outdir, name, id, a.input or ('text:' + a.text), packed, dev)

    print('wrote %s/  (%d frame%s, %d bytes)%s'
          % (outdir, len(packed), '' if len(packed) == 1 else 's',
             len(packed) * FRAME,
             '  [%d frames dropped: GIF had %d, limit %d]'
             % (len(raw) - len(frames), len(raw), a.frames) if dropped else ''))
    print('  for %s %s' % (dev['device'], dev['os']))
    print('  build:  python -m elekloader.sdk.build %s --stock <stock .syx>' % outdir)
    return 0


if __name__ == '__main__':
    sys.exit(main())
